### ISSUE TITLE
FlutterPluginNetworkPlugin

### ISSUE THREAD

**Issue by shownstrong** [cyndibaby905/44_flutter_plugin_network#1]
假设44_AndroidDemo是存在已久的原生工程，肯定有一份网络层代码，flutter模块用了plugin将网络请求转发给FlutterPluginNetworkPlugin，里面又有一份原生网络请求代码，那这样不就维护两份网络层代码了吗？     FlutterPluginNetworkPlugin 可以直接调用原生工程里的网络层代码吗？

**Comment by cyndibaby905** [comment]
你可以理解成Flutter层的网络代码（FlutterPluginNetworkPlugin）是Native的简单代理，核心逻辑（如通用参数、签名、错误拦截等）还是在Native
